apiVersion: apps/v1
kind: Deployment
metadata:
  name: restaurant-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: restaurant-frontend
  template:
    metadata:
      labels:
        app: restaurant-frontend
    spec:
      containers:
      - name: frontend
        image: docaash/devops-restaurant
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: NodePort
  selector:
    app: restaurant-frontend
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080  # You can choose any port between 30000-32767
